export const caseStudyDetails = {
  // 1. AN Tyres (UK)
  "antyres-uk": {
    id: "antyres-uk",
    company: "AN Tyres (UK)",
    title: "AN Tyres (UK) – Local SEO & Organic Growth Case Study",
    industry: "Automotive / Tyre Services",
    location: "Maidstone, UK",
    duration: "8 Months",
    publishedDate: "January 2024",
    overview:
      "AN Tyres is a UK-based automotive garage offering mobile tyre fitting, MOT, car servicing, brake repairs, and vehicle maintenance. I managed the complete Local SEO campaign for 8 months, focusing on increasing organic visibility, Google Business Profile performance, and lead generation across multiple service areas.",
    challenge:
      "When I joined the project, the website had limited organic visibility and the Google Business Profile wasn't generating its full potential. The goal was to increase local keyword rankings, improve Google Maps visibility, generate more customer calls, increase organic traffic, strengthen website authority, and improve AI search visibility.",
    solution:
      "I implemented a comprehensive SEO strategy covering Technical SEO (complete website audit, crawl & indexing optimization, internal linking improvements, schema markup implementation, Core Web Vitals optimization), Local SEO (Google Business Profile optimization, geo-targeted service pages, NAP consistency, local citation building, monthly review acquisition strategy), On-Page SEO (homepage optimization, service page optimization, meta titles & descriptions, heading structure, keyword clustering, content optimization, image SEO), and Off-Page SEO (high-quality backlink acquisition, local citations, guest posting, authority link building).",
    results: {
      traffic: "+181%",
      rankings: "+153%",
      leads: "+32.9%",
      keywords: "1,300+ ranking keywords",
    },
    detailedResults: {
      organicTraffic: "498 → 1,400+ Monthly Organic Visitors",
      organicKeywords: "514 → 1,300+ Ranking Keywords",
      impressions: "885K Impressions",
      clicks: "3.23K Clicks",
      gbpCalls: "1,361 Calls (+32.9%)",
      gbpInteractions: "3,440 Business Profile Interactions (+36.8%)",
    },
    keywordsRanked: [
      "Brake Repair Maidstone",
      "Full Car Service Maidstone",
      "Car Full Service Maidstone",
      "Part Worn Tyres Maidstone",
      "Cheap Part Worn Tyres Maidstone",
      "Mobile Tyre Fitting Maidstone",
      "MOT Testing Maidstone",
    ],
    strategy: [
      "Complete website audit and technical SEO optimization",
      "Crawl & indexing optimization with internal linking improvements",
      "Schema markup implementation for better SERP visibility",
      "Core Web Vitals optimization for improved user experience",
      "Google Business Profile optimization with regular updates",
      "Geo-targeted service pages and location pages",
      "Local citation building across 50+ UK directories",
      "Monthly review acquisition strategy",
      "Homepage and service page optimization",
      "Keyword clustering and content optimization",
      "High-quality backlink acquisition and authority building",
      "AI search visibility optimization",
    ],
    metrics: [
      { label: "Organic Traffic", before: "498/month", after: "1,400+/month" },
      { label: "Organic Keywords", before: "514", after: "1,300+" },
      { label: "GBP Calls", before: "1,024", after: "1,361" },
      { label: "GBP Interactions", before: "2,514", after: "3,440" },
    ],
    tools: [
      "Google Search Console",
      "Google Analytics 4",
      "Google Business Profile",
      "Ahrefs",
      "SEMrush",
      "Screaming Frog",
      "Rank Math",
      "Google Maps",
      "ChatGPT (SEO Workflow)",
      "Google AI Overview Optimization",
    ],
    images: {
      before: "/projects/Antyres/Semrush-before.png",
      after: "/projects/Antyres/Semrush-After.png",
      gallery: [
        "/projects/Antyres/GMB Calls (1).png",
        "/projects/Antyres/GMB Interaction.png",
        "/projects/Antyres/GSC.png",
      ],
    },
    testimonial:
      "Our visibility in local search has transformed completely. We're now getting consistent calls for all our services and have seen a significant increase in new customers. The team's expertise in local SEO has been invaluable.",
    testimonialAuthor: "Owner, AN Tyres (UK)",
    tags: ["Garage SEO", "Local SEO", "Technical SEO", "Citation Building"],
    url: "/case-studies/antyres-uk",
    highlights: [
      "181% increase in organic traffic (498 → 1.4K+)",
      "153% growth in ranking keywords (514 → 1.3K+)",
      "32.9% increase in Google Business Profile calls",
      "36.8% increase in Business Profile interactions",
      "Top rankings for high-intent local automotive keywords",
      "Improved AI search visibility through entity SEO and structured optimization",
    ],
  },

  // 2. Autoveto MOT
  "autoveto-mot": {
    id: "autoveto-mot",
    company: "Autoveto MOT",
    title: "Autoveto MOT – Local SEO Growth Case Study",
    industry: "Automotive / MOT Testing",
    location: "UK",
    duration: "4 Months",
    publishedDate: "February 2024",
    overview:
      "Autoveto MOT is a UK-based garage business providing MOT testing, car servicing, vehicle repairs, and local garage services. I managed the Local SEO and website optimization strategy with the goal of improving Google visibility, increasing local search traffic, and generating more calls from the Google Business Profile.",
    challenge:
      "Autoveto MOT needed to stand out in a competitive MOT testing market. With many testing centers nearby, they required a strategy that would make them the go-to choice for local vehicle owners. They had limited online presence and few customer reviews.",
    solution:
      "I focused on Google Business Profile optimization, review management, and local content creation to establish Autoveto MOT as the trusted local MOT center. Work included business category optimization, service updates, keyword-focused business description, regular GBP updates, review strategy improvement, local service targeting, meta title and description optimization, heading structure improvements, service keyword targeting, internal linking improvements, image SEO, content optimization for local intent, Google Search Console monitoring, indexing improvements, crawl issue checks, URL structure optimization, geo-targeted service page strategy, local keyword research, area-based keyword targeting, local citations, and NAP consistency.",
    results: {
      calls: "+60.2%",
      visibility: "+88.5%",
      leads: "+48.3%",
      keywords: "40+ keywords in top 3 positions",
    },
    detailedResults: {
      clicks: "327 → 485 (+48.3%)",
      impressions: "31.2K → 58.8K (+88.5%)",
      averagePosition: "20.2 → 15.1",
      gbpCalls: "197 calls (+60.2%)",
      gbpInteractions: "651 interactions",
    },
    keywordsRanked: [
      "MOT Test Near Me",
      "Class 4 MOT",
      "MOT Testing Center",
      "Car Service UK",
      "Vehicle Inspection",
      "MOT Booking",
    ],
    strategy: [
      "Google Business Profile optimization with complete information and photos",
      "Strategic review management and response system",
      "Local landing pages for service areas",
      "Competitor gap analysis and keyword targeting",
      "Enhanced service descriptions with local context",
      "Customer review generation and management",
      "Meta title and description optimization",
      "Heading structure improvements",
      "Image SEO and content optimization",
      "Google Search Console monitoring and indexing improvements",
    ],
    metrics: [
      { label: "Organic Clicks", before: "327", after: "485" },
      { label: "Search Impressions", before: "31.2K", after: "58.8K" },
      { label: "Average Position", before: "20.2", after: "15.1" },
      { label: "GBP Calls", before: "123", after: "197" },
    ],
    tools: [
      "Google Search Console",
      "Google Business Profile",
      "Google Analytics",
      "Ahrefs",
      "SEMrush",
      "Screaming Frog",
      "WordPress",
      "Local citation platforms",
    ],
    images: {
      before: "/projects/Autoveto/GMB Calls.png",
      after: "/projects/Autoveto/GMB Interaction.png",
      gallery: [
        "/projects/Autoveto/GMB Interaction.png",
        "/projects/Autoveto/GSC Stats.png",
      ],
    },
    testimonial:
      "The local SEO strategy has been game-changing. We're now the first choice for MOT testing in our area. The review management system has significantly improved our online reputation.",
    testimonialAuthor: "Manager, Autoveto MOT",
    tags: ["Local SEO", "GBP Optimization", "Review Management", "Geo Pages"],
    url: "/case-studies/autoveto-mot",
    highlights: [
      "Increased organic clicks by 48.3%",
      "Increased search impressions by 88.5%",
      "Improved average ranking position from 20.2 to 15.1",
      "Increased Google Business Profile calls by 60.2%",
      "Generated 197 customer calls from GBP",
      "Improved local keyword visibility",
    ],
  },

  // 3. Dominion Driving School
  "dominion-driving-school": {
    id: "dominion-driving-school",
    company: "Dominion Driving School",
    title: "Dominion Driving School – Canada SEO Growth Case Study",
    industry: "Education / Driving School",
    location: "Vancouver, Canada",
    duration: "8 Months",
    publishedDate: "January 2024",
    overview:
      "Dominion Driving School is a Canada-based driving school targeting students and learners looking for professional driving lessons, road test preparation, and driving-related services. I managed the SEO campaign with the goal of improving organic visibility, increasing website traffic, ranking local driving-related keywords, and generating more qualified visitors from Canada.",
    challenge:
      "Dominion Driving School needed to compete with established driving schools in Vancouver. They had limited online presence and needed to attract both new drivers and those seeking advanced training. The market was highly competitive with many established players.",
    solution:
      "I implemented a multi-channel SEO strategy including content marketing, social media integration, and comprehensive local SEO. Work included website audit, crawlability improvements, indexing issue monitoring, internal linking improvements, site structure optimization, meta title optimization, meta description optimization, heading structure improvements, keyword placement, content optimization, service page improvements, location-based keyword research, local landing page optimization, Google Business Profile support, local citation building, NAP consistency, city-based traffic targeting, content gap analysis, blog/content topic planning, keyword mapping, search intent optimization, FAQ-style content improvements, and entity-based SEO improvements.",
    results: {
      traffic: "+281%",
      rankings: "+55%",
      leads: "+175%",
      keywords: "1.5K+ organic keywords",
    },
    detailedResults: {
      organicTraffic: "54 → 206",
      organicKeywords: "559 → 1.5K",
      clicks: "91 → 868",
      impressions: "5.06K → 209K",
      averagePosition: "26.4 → 12.2",
      aiVisibility: "14 with 30 cited pages",
    },
    keywordsRanked: [
      "Driving School Vancouver",
      "Driving Lessons",
      "Behind the Wheel Training",
      "ICBC Approved School",
      "Driving Instructor",
      "New Driver Training",
      "Defensive Driving Course",
    ],
    strategy: [
      "Content marketing with blog posts about driving tips and safety",
      "Social media integration and review management",
      "Local citation building across Canadian directories",
      "ICBC-specific content and certification emphasis",
      "Video content for practical driving tips",
      "Student testimonial collection and display",
      "Website audit and crawlability improvements",
      "Internal linking and site structure optimization",
    ],
    metrics: [
      { label: "Organic Traffic", before: "54", after: "206" },
      { label: "Organic Keywords", before: "559", after: "1.5K" },
      { label: "Organic Clicks", before: "91", after: "868" },
      { label: "Average Position", before: "26.4", after: "12.2" },
    ],
    tools: [
      "Google Search Console",
      "Google Analytics 4",
      "SEMrush",
      "Ahrefs",
      "Screaming Frog",
      "Google Business Profile",
      "WordPress",
      "Rank Math / Yoast SEO",
      "Local Citation Platforms",
    ],
    images: {
      before: "/projects/Dominion Driving School/Before Smrush.png",
      after: "/projects/Dominion Driving School/After Smrush.png",
      gallery: [
        "/projects/Dominion Driving School/GA 4 - 1.png",
        "/projects/Dominion Driving School/GA 4 - 2.png",
        "/projects/Dominion Driving School/GA 4 - 3.png",
        "/projects/Dominion Driving School/GSC Stats.png",
      ],
    },
    testimonial:
      "We've seen an incredible increase in student enrollment. Our online presence has made us the trusted choice for driving education in Vancouver. The content strategy has really set us apart from competitors.",
    testimonialAuthor: "Owner, Dominion Driving School",
    tags: ["Local SEO", "Content Marketing", "Social Media", "Review Strategy"],
    url: "/case-studies/dominion-driving-school",
    highlights: [
      "868 organic clicks generated",
      "209K search impressions",
      "Active users and new users growth",
      "Organic search sessions increased",
      "Average position improved from 26.4 to 12.2",
      "Organic keywords increased from 559 to 1.5K",
      "Improved AI search visibility with 30 cited pages",
    ],
  },

  // 4. EM Bathrooms
  "em-bathrooms": {
    id: "em-bathrooms",
    company: "EM Bathrooms",
    title: "EM Bathrooms – UK SEO Growth Case Study",
    industry: "Home Services / Bathroom Fitting",
    location: "Southport, UK",
    duration: "5 Months",
    publishedDate: "February 2024",
    overview:
      "EM Bathrooms is a UK-based bathroom renovation and remodeling business targeting homeowners searching for bathroom design, renovation, and installation services. I managed the SEO campaign with the goal of improving organic visibility, increasing website traffic, building search authority, and generating more qualified local leads from the UK market.",
    challenge:
      "EM Bathrooms was losing business to larger bathroom fitting companies. They needed to establish their authority and visibility in the competitive London market. Their website wasn't converting visitors into leads effectively.",
    solution:
      "I combined on-page optimization, content marketing, and strategic link building to establish EM Bathrooms as a premium bathroom fitting service. Work included complete technical SEO audit, Google Search Console monitoring, crawl and indexation improvements, sitemap and robots.txt review, broken link checking, page speed and Core Web Vitals review, URL structure improvements, schema markup recommendations, meta title optimization, meta description optimization, heading structure improvements, service page keyword targeting, content optimization, image SEO, internal linking between related service pages, search intent alignment, local keyword research, service-area page optimization, location-based SEO strategy, local citation building, NAP consistency, Google Business Profile support, content gap analysis, keyword mapping, blog/content topic planning, FAQ-based content improvements, semantic SEO optimization, and search-intent focused content updates.",
    results: {
      traffic: "+186.2%",
      rankings: "+60%",
      leads: "+190%",
      keywords: "1.5K organic keywords",
    },
    detailedResults: {
      activeUsers: "1.3K (+186.2%)",
      events: "6.8K (+161.1%)",
      newUsers: "1.3K (+185.1%)",
      clicks: "91 → 868",
      impressions: "5.06K → 209K",
      averagePosition: "26.4 → 12.2",
      organicTraffic: "54 → 206",
      organicKeywords: "559 → 1.5K",
    },
    keywordsRanked: [
      "Bathroom Fitters London",
      "Bathroom Renovation",
      "Wet Room Installation",
      "Bathroom Design",
      "Bathroom Installation",
      "Luxury Bathrooms London",
    ],
    strategy: [
      "Service page optimization with detailed descriptions and images",
      "Content strategy including bathroom design tips and trends",
      "Quality backlink building from home improvement sites",
      "Local directory listing and citation optimization",
      "Before and after gallery optimization",
      "Customer review and testimonial collection",
      "Complete technical SEO audit and fixes",
      "Schema markup implementation",
      "Search intent alignment and semantic SEO",
    ],
    metrics: [
      { label: "Active Users", before: "700", after: "1.3K" },
      { label: "Organic Traffic", before: "54", after: "206" },
      { label: "Organic Keywords", before: "559", after: "1.5K" },
      { label: "Average Position", before: "26.4", after: "12.2" },
    ],
    tools: [
      "Google Analytics 4",
      "Google Search Console",
      "SEMrush",
      "Ahrefs",
      "Screaming Frog",
      "Google Business Profile",
      "WordPress",
      "Rank Math / Yoast SEO",
      "Local citation platforms",
    ],
    images: {
      before: "/projects/EmBathrooms/Semrush Before.png",
      after: "/projects/EmBathrooms/Semrush After.png",
      gallery: [
        "/projects/EmBathrooms/GA 4 1.png",
        "/projects/EmBathrooms/GA 4 2.png",
        "/projects/EmBathrooms/GSC.png"
      ],
    },
    testimonial:
      "Our phone hasn't stopped ringing since we implemented the SEO strategy. We're now getting high-quality leads for premium bathroom projects. The content strategy has really showcased our expertise.",
    testimonialAuthor: "Director, EM Bathrooms",
    tags: ["Local SEO", "On-Page SEO", "Content Strategy", "Link Building"],
    url: "/case-studies/em-bathrooms",
    highlights: [
      "868 organic clicks generated",
      "209K search impressions",
      "1.3K active users",
      "Organic search sessions increased",
      "Average position improved from 26.4 to 12.2",
      "Organic keywords increased from 559 to 1.5K",
      "303 backlinks built/maintained",
      "137 referring domains",
    ],
  },

  // 5. Kent Mobile Tyre Services
  "kent-mobile-tyre-services": {
    id: "kent-mobile-tyre-services",
    company: "Kent Mobile Tyre Services",
    title: "Kent Mobile Tyre Services – Local SEO & Organic Growth Case Study",
    industry: "Automotive / Mobile Tyre Fitting",
    location: "Kent, UK",
    duration: "6 Months",
    publishedDate: "January 2024",
    overview:
      "Kent Mobile Tyre Services is a UK-based mobile tyre fitting business providing tyre fitting, tyre repair, puncture repair, and emergency mobile tyre services across Kent and nearby areas. I managed the SEO campaign with a strong focus on Local SEO, Google Business Profile optimization, technical SEO, content optimization, geo-targeted pages, and authority-building strategies to improve rankings, increase visibility, and generate more customer calls.",
    challenge:
      "Kent Mobile Tyre Services needed to dominate the mobile tyre fitting market in Kent. They were facing competition from both national chains and local mechanics. Their emergency service wasn't being seen by potential customers.",
    solution:
      "I implemented a hyper-local SEO strategy with GBP optimization, geo-targeted pages, and a comprehensive review management system. Work included GBP category optimization, service updates, keyword-focused business description, regular Google Posts, local service area optimization, review strategy improvement, mobile tyre fitting location pages, emergency tyre fitting location pages, same-day tyre fitting pages, puncture repair location targeting, area-based keyword mapping, internal linking between service and location pages, meta title optimization, meta description optimization, heading structure improvements, keyword placement, image SEO, local content optimization, internal linking improvements, service page optimization, Google Search Console monitoring, crawl and indexing improvements, broken link checks, sitemap and robots.txt review, Core Web Vitals checks, schema markup recommendations, URL structure improvements, local citation building, NAP consistency, guest posting, competitor backlink analysis, authority backlink building, business profile creation, and local directory submissions.",
    results: {
      calls: "+9.4%",
      visibility: "+1,765%",
      leads: "+429.2%",
      keywords: "2.7K+ organic keywords",
    },
    detailedResults: {
      activeUsers: "33K (+429.2%)",
      events: "179K (+332.5%)",
      engagedSessions: "22K (+401.5%)",
      newUsers: "33K (+421.4%)",
      organicSessions: "15K (+1,765%)",
      clicks: "7.18K",
      impressions: "1.25M",
      averagePosition: "13.3 → 10.9",
      gbpCalls: "396 (+9.4%)",
      gbpInteractions: "1,193 (+7.8%)",
      organicTraffic: "290 → 1.4K",
      organicKeywords: "1.4K → 2.7K",
    },
    keywordsRanked: [
      "Mobile Tyre Fitting Kent",
      "24/7 Tyre Service",
      "Emergency Tyre Repair",
      "Mobile Mechanic Kent",
      "Tyre Replacement",
      "Same Day Tyre Fitting",
      "Mobile Tyre Fitting Near Me",
      "Mobile Puncture Repair Kent",
    ],
    strategy: [
      "Location-specific landing pages for each service area",
      "Google Business Profile optimization with 24/7 availability",
      "Review strategy emphasizing emergency response time",
      "Mobile-friendly design with instant booking functionality",
      "Local citation building across Kent directories",
      "Emergency service promotion and visibility",
      "GBP category optimization and regular updates",
      "Area-based keyword mapping and targeting",
    ],
    metrics: [
      { label: "Active Users", before: "7.7K", after: "33K" },
      { label: "Organic Sessions", before: "850", after: "15K" },
      { label: "Organic Traffic", before: "290", after: "1.4K" },
      { label: "Organic Keywords", before: "1.4K", after: "2.7K" },
    ],
    tools: [
      "Google Analytics 4",
      "Google Search Console",
      "Google Business Profile",
      "SEMrush",
      "Ahrefs",
      "Screaming Frog",
      "WordPress",
      "Rank Math / Yoast SEO",
      "Local citation platforms",
      "Google Maps",
      "Bright Local",
    ],
    images: {
      before: "/projects/Kent Mobile tyre Services/Semrush Before.png",
      after: "/projects/Kent Mobile tyre Services/Semrush After.png",
      gallery: [
        "/projects/Kent Mobile tyre Services/Calls GMB.png",
        "/projects/Kent Mobile tyre Services/GA 4 - 1.png",
        "/projects/Kent Mobile tyre Services/GA 4 - 2.png",
        "/projects/Kent Mobile tyre Services/GSC Stats.png",
        "/projects/Kent Mobile tyre Services/Interaction GMB.png",
        "/projects/Kent Mobile tyre Services/Mobile tyre Fitting Kent.png",
        "/projects/Kent Mobile tyre Services/Near Me Ranking.png",
      ],
    },
    testimonial:
      "We're now the first call for emergency tyre services in Kent. The SEO strategy has transformed our business completely. Our response times have improved and we're covering more areas than ever.",
    testimonialAuthor: "Owner, Kent Mobile Tyre Services",
    tags: [
      "Local SEO",
      "GBP Optimization",
      "Geo Pages",
      "Citation Building",
      "Reviews Strategy",
    ],
    url: "/case-studies/kent-mobile-tyre-services",
    highlights: [
      "33K active users generated",
      "429.2% growth in active users",
      "15K organic search sessions",
      "1,765% growth in organic search sessions",
      "396 calls from Google Business Profile",
      "1.25M Google Search impressions",
      "Average position improved from 13.3 to 10.9",
      "Organic keywords increased from 1.4K to 2.7K",
      "AI visibility improved with 178 cited pages",
    ],
  },

  // 6. Mobile Tyre Service London
  "mobile-tyre-service-london": {
    id: "mobile-tyre-service-london",
    company: "Mobile Tyre Service London",
    title: "Mobile Tyre Services – London SEO Growth Case Study",
    industry: "Automotive / Mobile Tyre Fitting",
    location: "London, UK",
    duration: "5 Months",
    publishedDate: "February 2024",
    overview:
      "Mobile Tyre Services is a London-based mobile tyre fitting business providing emergency tyre fitting, mobile puncture repair, tyre replacement, and 24/7 roadside tyre assistance across London. I managed the SEO campaign with a strong focus on Local SEO, Technical SEO, Google Business Profile optimization, on-page SEO, service-area targeting, and authority building to improve search visibility, keyword rankings, and customer leads.",
    challenge:
      "In the competitive London market, Mobile Tyre Service London needed to stand out. They required a strategy that would make them the preferred choice for mobile tyre fitting across the capital. They had limited visibility in specific boroughs.",
    solution:
      "I optimized their Google Business Profile, created geo-targeted pages for each London borough, and implemented a comprehensive review strategy focusing on response times and service quality. Work included business category optimization, service updates, keyword-focused GBP description, regular Google Posts, local service area targeting, review strategy support, London keyword targeting, service-area page optimization, local search intent optimization, internal linking between service pages, NAP consistency, local citation building, Google Maps ranking improvement, meta title optimization, meta description optimization, heading structure improvement, keyword placement, image SEO, URL structure optimization, internal linking improvements, content optimization, Google Search Console monitoring, crawl and indexing improvements, sitemap and robots.txt review, broken link checks, schema markup recommendations, page performance review, technical SEO fixes, local citation building, guest posting, business profile backlinks, competitor backlink analysis, authority backlink building, and niche-relevant link acquisition.",
    results: {
      calls: "+35.2%",
      visibility: "+200%",
      leads: "+150%",
      keywords: "281+ organic keywords",
    },
    detailedResults: {
      clicks: "32 → 751",
      impressions: "2.82K → 186K",
      averagePosition: "15.9 → 10.9",
      gbpCalls: "133 calls",
      gbpInteractions: "414 interactions",
      organicTraffic: "0 → 81",
      organicKeywords: "8 → 281",
      aiCitedPages: "9 → 46",
    },
    keywordsRanked: [
      "Mobile Tyre Fitting London",
      "Same Day Tyre Service",
      "Emergency Tyre Repair",
      "24/7 Mobile Tyre Service",
      "Tyre Fitting Near Me",
      "Mobile Tyres London",
      "Mobile Puncture Repair London",
      "Tyre Puncture Repair London",
    ],
    strategy: [
      "London-specific service pages with borough targeting",
      "Google Business Profile optimization with before/after images",
      "24/7 emergency service emphasis in all content",
      "Review response strategy highlighting speed and reliability",
      "Competitor gap analysis for London market",
      "Mobile booking system implementation",
      "Local citation building across London directories",
      "Service-area page optimization for each borough",
    ],
    metrics: [
      { label: "Organic Clicks", before: "32", after: "751" },
      { label: "Search Impressions", before: "2.82K", after: "186K" },
      { label: "Average Position", before: "15.9", after: "10.9" },
      { label: "Organic Keywords", before: "8", after: "281" },
    ],
    tools: [
      "Google Search Console",
      "Google Analytics 4",
      "Google Business Profile",
      "SEMrush",
      "Ahrefs",
      "Screaming Frog",
      "WordPress",
      "Rank Math / Yoast SEO",
      "Local citation platforms",
      "Google Maps",
    ],
    images: {
      before: "/projects/Mobile tyre Services Ltd/Semrush Before.png",
      after: "/projects/Mobile tyre Services Ltd/Semrush After.png",
      gallery: [
        "/projects/Mobile tyre Services Ltd/GMB Calls.png",
        "/projects/Mobile tyre Services Ltd/GMB Interaction.png",
        "/projects/Mobile tyre Services Ltd/GSC.png",
        "/projects/Mobile tyre Services Ltd/SERP Ranking 1.png",
        "/projects/Mobile tyre Services Ltd/SERP Ranking(1).png",
        "/projects/Mobile tyre Services Ltd/SERP Ranking.png",
      ],
    },
    testimonial:
      "Our London coverage is now comprehensive, and we're getting consistent calls from all over the city. The SEO work has been exceptional. We're now the go-to mobile tyre service in London.",
    testimonialAuthor: "Managing Director, Mobile Tyre Service London",
    tags: [
      "Local SEO",
      "GBP Optimization",
      "Geo Pages",
      "Citation Building",
      "Reviews Strategy",
    ],
    url: "/case-studies/mobile-tyre-service-london",
    highlights: [
      "751 organic clicks generated",
      "186K search impressions",
      "Average position improved from 15.9 to 10.9",
      "133 calls from Google Business Profile",
      "414 business profile interactions",
      "Organic keywords increased from 8 to 281",
      "Organic traffic grew from 0 to 81",
      "AI cited pages increased from 9 to 46",
    ],
  },

// 7. PoppyLane Clothing
"poppylane-clothing": {
  id: "poppylane-clothing",
  company: "PoppyLane Clothing",
  title: "PoppyLane Clothing – Ireland eCommerce SEO Growth Case Study",
  industry: "Fashion / E-Commerce",
  location: "Ireland",
  duration: "Ongoing",
  publishedDate: "March 2024",
  overview:
    "PoppyLane Clothing is an Ireland-based Shopify fashion eCommerce store offering women's clothing, tops, jeans, coats, dresses, trousers, knitwear, and seasonal fashion collections. I managed the SEO campaign with a strong focus on eCommerce SEO, Shopify SEO, category page optimization, content optimization, internal linking, keyword rankings, and revenue growth. The main goal was to improve organic visibility, rank commercial fashion keywords, and increase sales through SEO-driven traffic.",
  challenge:
    "PoppyLane Clothing needed to compete in the competitive Irish fashion market. They had limited organic visibility and needed to rank for commercial fashion keywords that would drive actual sales. The Shopify store needed optimization for both search engines and user experience.",
  solution:
    "I implemented a comprehensive eCommerce SEO strategy including Shopify SEO optimization (homepage SEO, collection/category page optimization, product page SEO improvements, meta titles and descriptions, heading structure improvements, image alt text optimization, Shopify URL and content structure improvements), Category Page SEO (optimized high-value collection pages including Women's Tops, Jeans, Coats, Dresses, Knitwear, Trousers, and seasonal fashion collections), Content & Blog SEO (fashion trend keyword research, blog topic planning, content optimization, internal linking from blogs to collections, seasonal keyword targeting, search intent alignment), and Off-Page SEO & Link Building (guest posting, fashion niche backlinks, business profile links, competitor backlink analysis, internal authority distribution, collection page authority improvement).",
  results: {
    traffic: "+240.6%",
    rankings: "+105%",
    leads: "+167%",
    keywords: "428+ ranking keywords",
  },
  detailedResults: {
    revenue: "€3K → €14.8K",
    orders: "108 → 292",
    newUsers: "19K (+103.1%)",
    activeUsers: "19K (+103.5%)",
    engagedSessions: "15K (+116%)",
    organicSessions: "10K (+240.6%)",
    organicShopping: "579 (+597.6%)",
    conversionRate: "1.07%",
  },
  keywordsRanked: [
    "womens tops Ireland — Position 1",
    "coat — Position 2",
    "jeans Ireland — Position 2",
    "Sligo clothes shops — Position 2",
    "jumper clothing — Position 3",
    "fit jeans — Position 5",
    "Ireland clothing brands — Position 5",
    "ladies tops Ireland — Position 6",
    "jean — Position 7",
  ],
  strategy: [
    "Homepage SEO optimization",
    "Collection/category page optimization",
    "Product page SEO improvements",
    "Meta titles and meta descriptions optimization",
    "Heading structure improvements",
    "Image alt text optimization",
    "Shopify URL and content structure improvements",
    "Fashion trend keyword research",
    "Blog topic planning and content optimization",
    "Internal linking from blogs to collections",
    "Seasonal keyword targeting",
    "Search intent alignment",
    "Guest posting and fashion niche backlinks",
    "Business profile links",
    "Competitor backlink analysis",
    "Internal authority distribution",
  ],
  metrics: [
    { label: "Revenue", before: "€3K", after: "€14.8K" },
    { label: "Orders", before: "108", after: "292" },
    { label: "Active Users", before: "9.3K", after: "19K" },
    { label: "Organic Sessions", before: "2.9K", after: "10K" },
  ],
  tools: [
    "Shopify",
    "Google Analytics 4",
    "Google Search Console",
    "SEMrush",
    "Ahrefs",
    "Screaming Frog",
    "Google Keyword Planner",
    "Rank Math / Shopify SEO apps",
    "Content optimization tools",
  ],
  images: {
    before: "/projects/Poppylane Clothing/Semrush before.png",
    after: "/projects/Poppylane Clothing/Semrush after.png",
    gallery: [
      "/projects/Poppylane Clothing/GA 4 - 1.png",
      "/projects/Poppylane Clothing/GA 4 - 2.png",
      "/projects/Poppylane Clothing/GA 4 - 3.png",
      "/projects/Poppylane Clothing/GSC.png",
      "/projects/Poppylane Clothing/SERP Ranking .png",
      "/projects/Poppylane Clothing/SERP Ranking 1.png",
      "/projects/Poppylane Clothing/Serp ranking 2.png",
      "/projects/Poppylane Clothing/Serp ranking 3.png",
      "/projects/Poppylane Clothing/Shopify.png",
      "/projects/Poppylane Clothing/Traffic Channel.png",
      "/projects/Poppylane Clothing/page Views.png",
    ],
  },
  testimonial:
    "Our Shopify store has seen incredible growth since implementing the SEO strategy. We've gone from €3K to nearly €15K in revenue, and our organic visibility has improved dramatically. The team's understanding of eCommerce SEO has been outstanding.",
  testimonialAuthor: "Owner, PoppyLane Clothing",
  tags: ["eCommerce SEO", "Shopify SEO", "Fashion SEO", "Revenue Growth"],
  url: "/case-studies/poppylane-clothing",
  highlights: [
    "🚀 Revenue increased from €3K to €14.8K",
    "🛒 292 orders generated (+170%)",
    "👥 19K active users (+103.5%)",
    "📊 10K organic search sessions (+240.6%)",
    "🛍️ Organic shopping sessions grew +597.6%",
    "🥇 Position 1 for 'womens tops Ireland'",
    "🥈 Position 2 for 'jeans Ireland'",
    "🥈 Position 2 for 'Sligo clothes shops'",
    "Strong rankings for coats, tops, jeans, and fashion keywords",
    "Improved authority through link building and internal linking",
  ],
},

// 8. Sussex Tyre Services
"sussex-tyre-services": {
  id: "sussex-tyre-services",
  company: "Sussex Tyre Services",
  title: "Sussex Tyre Services – Local SEO Growth Case Study",
  industry: "Automotive / Tyre Services",
  location: "Worthing, UK",
  duration: "Ongoing",
  publishedDate: "March 2024",
  overview:
    "Sussex Tyre Services is a UK-based tyre shop in Worthing, offering tyre fitting, puncture repair, mobile tyre services, new tyres, budget tyres, premium tyres, and related automotive services. I managed the SEO campaign with a focus on Local SEO, Google Business Profile optimization, on-page SEO, technical SEO, location-based keyword targeting, and organic visibility growth.",
  challenge:
    "Sussex Tyre Services needed to improve visibility for tyre-related searches in Worthing. They were competing with both national chains and local garages. Their Google Business Profile and website needed optimization to attract more local customers.",
  solution:
    "I implemented a Local SEO strategy focused on Google Business Profile optimization, local keyword targeting, on-page SEO, technical SEO, and local authority building. Work included GBP category optimization, service list optimization, business description improvements, regular GBP updates, local keyword targeting, review strategy support, performance tracking, meta title optimization, meta description optimization, heading structure improvements, local keyword placement, internal linking improvements, image SEO, service page content optimization, URL structure improvements, Google Search Console monitoring, crawl and indexing checks, sitemap review, robots.txt review, broken link checks, page performance review, schema markup recommendations, local citation building, NAP consistency, business profile creation, local backlink opportunities, competitor analysis, and authority-building strategy.",
  results: {
    traffic: "+498%",
    rankings: "+235%",
    leads: "+172%",
    keywords: "40+ keywords in top 3 positions",
  },
  detailedResults: {
    clicks: "197 → 660",
    impressions: "20.9K → 125K",
    averagePosition: "23 → 12.9",
    gbpCalls: "172 calls",
    gbpInteractions: "1,041 interactions",
  },
  keywordsRanked: [
    "Tyre fitting Worthing — Google Maps",
    "Tyres Worthing — Google Maps",
    "Puncture repair Worthing — Position 1 (Organic)",
    "Mobile tyre fitting Worthing",
    "New tyres Worthing",
    "Budget tyres Worthing",
    "Premium tyres Worthing",
  ],
  strategy: [
    "GBP category optimization",
    "Service list optimization",
    "Business description improvements",
    "Regular GBP updates",
    "Local keyword targeting",
    "Review strategy support",
    "Performance tracking for calls and interactions",
    "Meta title optimization",
    "Meta description optimization",
    "Heading structure improvements",
    "Local keyword placement",
    "Internal linking improvements",
    "Image SEO",
    "Service page content optimization",
    "URL structure improvements",
    "Google Search Console monitoring",
    "Local citation building",
    "NAP consistency",
    "Business profile creation",
    "Local backlink opportunities",
  ],
  metrics: [
    { label: "Organic Clicks", before: "197", after: "660" },
    { label: "Search Impressions", before: "20.9K", after: "125K" },
    { label: "Average Position", before: "23", after: "12.9" },
    { label: "GBP Calls", before: "N/A", after: "172" },
  ],
  tools: [
    "Google Search Console",
    "Google Business Profile",
    "Google Analytics 4",
    "SEMrush",
    "Ahrefs",
    "Screaming Frog",
    "WordPress",
    "Rank Math / Yoast SEO",
    "Local citation platforms",
    "Google Maps",
  ],
  images: {
    before: "/projects/Sussex Tyre Services/GMB Calls.png",
    after: "/projects/Sussex Tyre Services/GMB Interaction.png",
    gallery: [
      "/projects/Sussex Tyre Services/GMB Calls.png",
      "/projects/Sussex Tyre Services/GMB Interaction.png",
      "/projects/Sussex Tyre Services/GSC.png",
    ],
  },
  testimonial:
    "Our visibility in Worthing has improved dramatically. We're getting consistent calls from Google Business Profile and our website is now ranking on the first page for important tyre services. The local SEO strategy has really delivered results.",
  testimonialAuthor: "Owner, Sussex Tyre Services",
  tags: ["Local SEO", "GBP Optimization", "Citation Building", "On-Page SEO"],
  url: "/case-studies/sussex-tyre-services",
  highlights: [
    "🚀 660 organic clicks generated (+235%)",
    "📈 125K Google Search impressions (+498%)",
    "🔍 Average position improved from 23 to 12.9",
    "📞 172 calls from Google Business Profile",
    "📍 1,041 Google Business Profile interactions",
    "🛞 Ranked for tyre-related Worthing keywords",
    "📌 Google Maps visibility for 'Tyre fitting Worthing' and 'Tyres Worthing'",
    "🌐 First-page organic visibility for 'Puncture repair Worthing'",
  ],
},

// 9. The Tyre Shop Harlow
"the-tyre-shop-harlow": {
  id: "the-tyre-shop-harlow",
  company: "The Tyre Shop Harlow",
  title: "The Tyre Shop Harlow – Local SEO Growth Case Study",
  industry: "Automotive / Tyre Services",
  location: "Harlow, UK",
  duration: "Ongoing",
  publishedDate: "March 2024",
  overview:
    "The Tyre Shop Harlow is a UK-based tyre service business offering tyre fitting, mobile tyre fitting, emergency tyre services, part-worn tyres, and vehicle-related tyre solutions in Harlow. I managed the SEO campaign with a focus on Local SEO, Google rankings, technical SEO, on-page optimization, service-page optimization, and organic visibility growth to improve search performance and attract more local customers.",
  challenge:
    "The Tyre Shop Harlow needed to improve visibility for tyre-related searches in Harlow. They were losing customers to competitors and needed to establish themselves as the go-to tyre service provider in the area.",
  solution:
    "I implemented a Local SEO strategy focused on ranking local tyre keywords, improving organic traffic, increasing Google Search visibility, optimizing service pages, improving average keyword position, strengthening local SEO signals, and building authority through backlinks and citations. Work included local SEO targeting (tyre fitting Harlow, tyres Harlow, tyre shop near me, mobile tyre fitting Harlow, part worn tyres Harlow, emergency tyre service Harlow), on-page SEO (meta title optimization, meta description optimization, heading structure improvement, local keyword placement, internal linking improvements, service page content optimization, image SEO, URL structure optimization), technical SEO (Google Search Console monitoring, crawl and indexing checks, sitemap review, robots.txt checks, broken link analysis, page structure improvements), and off-page SEO & authority building (local citation building, business profile creation, NAP consistency, competitor backlink analysis, link-building opportunities, local directory submissions).",
  results: {
    traffic: "+21.4%",
    rankings: "+26.5%",
    leads: "+105%",
    keywords: "428+ ranking keywords",
  },
  detailedResults: {
    activeUsers: "4.9K (+5.9%)",
    newUsers: "4.9K (+6.2%)",
    sessions: "5.5K (+8.0%)",
    organicSessions: "1.6K (+21.4%)",
    clicks: "1.15K → 1.36K (+18.2%)",
    impressions: "137K → 136K",
    averagePosition: "29.7 → 20.6",
    organicTraffic: "152 → 312",
    organicKeywords: "338 → 428",
    authorityScore: "17",
    referringDomains: "522",
    backlinks: "6.9K",
    aiVisibility: "14",
    aiMentions: "2",
  },
  keywordsRanked: [
    "Tyre fitting Harlow — Position 1",
    "Tyre shop near me — Position 1",
    "Tyres Harlow — Position 1",
  ],
  strategy: [
    "Local keyword targeting for Harlow-based searches",
    "Meta title and description optimization",
    "Heading structure improvement",
    "Local keyword placement",
    "Internal linking improvements",
    "Service page content optimization",
    "Image SEO",
    "URL structure optimization",
    "Google Search Console monitoring",
    "Crawl and indexing checks",
    "Sitemap and robots.txt review",
    "Broken link analysis",
    "Local citation building",
    "Business profile creation",
    "NAP consistency",
    "Competitor backlink analysis",
  ],
  metrics: [
    { label: "Active Users", before: "4.6K", after: "4.9K" },
    { label: "Sessions", before: "5.1K", after: "5.5K" },
    { label: "Organic Sessions", before: "1.3K", after: "1.6K" },
    { label: "Organic Traffic", before: "152", after: "312" },
  ],
  tools: [
    "Google Analytics 4",
    "Google Search Console",
    "SEMrush",
    "Ahrefs",
    "Screaming Frog",
    "WordPress",
    "Google Business Profile",
    "Local citation platforms",
    "Rank Math / Yoast SEO",
  ],
  images: {
    before: "/projects/The Tyre Shop Harlo/Semrush before.png",
    after: "/projects/The Tyre Shop Harlo/Semrush After.png",
    gallery: [
      "/projects/The Tyre Shop Harlo/GA4 - 1.png",
      "/projects/The Tyre Shop Harlo/GA4 - 2.png",
      "/projects/The Tyre Shop Harlo/GSC.png",
    ],
  },
  testimonial:
    "The SEO work has transformed our online presence. We're now ranking position 1 for 'Tyre fitting Harlow' and other key terms. Our customers can easily find us online, and we're seeing consistent traffic growth.",
  testimonialAuthor: "Owner, The Tyre Shop Harlow",
  tags: ["Local SEO", "Technical SEO", "Citation Building", "On-Page SEO"],
  url: "/case-studies/the-tyre-shop-harlow",
  highlights: [
    "🚀 4.9K active users",
    "👥 4.9K new users",
    "📊 5.5K sessions",
    "🔍 1.36K organic clicks (+18.2%)",
    "📈 136K search impressions",
    "📌 Average position improved from 29.7 to 20.6",
    "📊 Organic Search sessions increased by +21.4%",
    "🔑 Organic keywords increased from 338 to 428",
    "🌐 Organic traffic improved from 152 to 312",
    "🥇 Position 1 for 'Tyre fitting Harlow'",
    "🥇 Position 1 for 'Tyre shop near me'",
    "🥇 Position 1 for 'Tyres Harlow'",
    "🤖 AI visibility achieved with 14 mentions",
  ],
},

// 10. Mobile Tyres Team Crawley
"mobile-tyres-team-crawley": {
  id: "mobile-tyres-team-crawley",
  company: "Mobile Tyres Team Crawley",
  title: "Mobile Tyres Team Crawley – Local SEO Growth Case Study",
  industry: "Automotive / Mobile Tyre Fitting",
  location: "Crawley, UK",
  duration: "Ongoing",
  publishedDate: "March 2024",
  overview:
    "Mobile Tyres Team Crawley is a UK-based mobile tyre fitting and emergency tyre replacement business serving Crawley, Horley, Burgess Hill, and nearby areas. The business provides 24/7 mobile tyre fitting, puncture repair, emergency tyre call-outs, and roadside tyre replacement services. I managed the SEO campaign with a focus on Local SEO, Google Business Profile optimization, service-area pages, on-page SEO, technical SEO, and local ranking growth to improve visibility and generate more customer calls.",
  challenge:
    "Mobile Tyres Team Crawley needed to improve visibility across multiple service areas. They were missing out on emergency tyre fitting calls because their Google Business Profile and website weren't optimized for local searches in Crawley and surrounding areas.",
  solution:
    "I implemented a Local SEO strategy focused on Google Business Profile optimization, service-area page creation, local keyword targeting, on-page SEO, technical SEO, and local authority building. Work included GBP category optimization, service list optimization, keyword-focused business description, local service area targeting, regular Google updates/posts, review strategy support, tracking calls and customer interactions, service-area page optimization for Crawley, Horley, Burgess Hill, and nearby areas, meta title and description optimization, heading structure improvements, local keyword placement, internal linking between service pages, image SEO, content optimization, URL structure improvements, Google Search Console monitoring, crawl and indexing checks, sitemap review, robots.txt checks, broken link checks, technical SEO recommendations, page structure improvements, local citation building, business profile submissions, NAP consistency, competitor backlink analysis, local backlink opportunities, and authority-building strategy.",
  results: {
    traffic: "+80.6%",
    rankings: "+242.3%",
    leads: "+344.8%",
    keywords: "60+ keywords in top 3 positions",
  },
  detailedResults: {
    gbpCalls: "67 → 298 (+344.8%)",
    gbpInteractions: "291 → 996 (+242.3%)",
    clicks: "278 → 502 (+80.6%)",
    impressions: "33.5K → 44.8K (+33.7%)",
    averagePosition: "42.9 → 17.9",
  },
  keywordsRanked: [
    "Mobile tyre fitting Crawley — Google Maps",
    "Mobile tyre fitting near Crawley — Google Maps",
    "Emergency mobile tyre Crawley — Google Maps",
    "Mobile tyre fitting Horley — Organic",
    "Mobile tyre fitting Burgess Hill — Organic",
    "24/7 mobile tyre fitting Crawley — Organic",
  ],
  strategy: [
    "GBP category optimization",
    "Service list optimization",
    "Keyword-focused business description",
    "Local service area targeting",
    "Regular Google updates/posts",
    "Review strategy support",
    "Tracking calls and customer interactions",
    "Service-area page optimization for multiple locations",
    "Meta title and description optimization",
    "Heading structure improvements",
    "Local keyword placement",
    "Internal linking between service pages",
    "Image SEO and content optimization",
    "URL structure improvements",
    "Google Search Console monitoring",
    "Crawl and indexing checks",
    "Local citation building",
    "NAP consistency",
    "Business profile submissions",
    "Local backlink opportunities",
  ],
  metrics: [
    { label: "GBP Calls", before: "67", after: "298" },
    { label: "GBP Interactions", before: "291", after: "996" },
    { label: "Organic Clicks", before: "278", after: "502" },
    { label: "Average Position", before: "42.9", after: "17.9" },
  ],
  tools: [
    "Google Search Console",
    "Google Business Profile",
    "Google Analytics 4",
    "SEMrush",
    "Ahrefs",
    "Screaming Frog",
    "WordPress",
    "Rank Math / Yoast SEO",
    "Local citation platforms",
    "Google Maps",
  ],
  images: {
    before: "/projects/Mobile Tyre team Crawley/GMB Calls.png",
    after: "/projects/Mobile Tyre team Crawley/GMB Interaction.png",
    gallery: [
      "/projects/Mobile Tyre team Crawley/GMB Calls.png",
      "/projects/Mobile Tyre team Crawley/GMB Interaction.png",
      "/projects/Mobile Tyre team Crawley/GSC.png",
    ],
  },
  testimonial:
    "Our Google Business Profile calls have more than tripled since implementing the SEO strategy. We're now the go-to mobile tyre service in Crawley and surrounding areas. The service-area pages have really helped us expand our reach.",
  testimonialAuthor: "Owner, Mobile Tyres Team Crawley",
  tags: [
    "Local SEO",
    "GBP Optimization",
    "Service Pages",
    "Citation Building",
  ],
  url: "/case-studies/mobile-tyres-team-crawley",
  highlights: [
    "📞 298 calls from Google Business Profile (+344.8%)",
    "📍 996 Google Business Profile interactions (+242.3%)",
    "🔍 502 organic clicks (+80.6%)",
    "📊 44.8K search impressions (+33.7%)",
    "📌 Average position improved from 42.9 to 17.9",
    "🛞 Ranked for 'Mobile tyre fitting Crawley'",
    "🌍 Improved visibility for Horley and Burgess Hill service pages",
    "🔧 Strong Local SEO growth for a UK mobile tyre business",
  ],
},
};
